package ditda.backend.global.notification;

public enum NotificationType {

	// 지원 마감 (ApplicationDeadlineClosed)
	APPLICATION_REFUND_REQUEST_ADMIN,
	APPLICATION_CANCELLED_INSTRUCTOR,
	APPLICATION_SHORTFALL_INSTRUCTOR,
	APPLICATION_MATCHED_INSTRUCTOR,
	APPLICATION_MATCHED_DESIGNER,

	// 1차 시안 마감 (FirstDraftDeadlineClosed)
	FIRST_DRAFT_REFUND_REQUEST_ADMIN,
	FIRST_DRAFT_ZERO_INSTRUCTOR,
	FIRST_DRAFT_SHORTFALL_INSTRUCTOR,
	FIRST_DRAFT_MISSED_DESIGNER,

	// 최종 마감 (FinalDeadlineClosed)
	FINAL_CANCELLED_INSTRUCTOR,
	FINAL_CANCELLED_DESIGNER,

	// 전원 1차 시안 제출 (AllFirstDraftsSubmitted)
	ALL_FIRST_DRAFTS_SUBMITTED_INSTRUCTOR,

	// 시안 선택 (DraftSelected)
	DRAFT_SELECTED_DESIGNER,
	DRAFT_REJECTED_DESIGNER,

	// 외주 최종 확정 (CommissionCompleted)
	COMMISSION_FINALIZED_INSTRUCTOR,
	COMMISSION_FINALIZED_DESIGNER,

	// 수정 요청/제출 (RevisionRequested / RevisionSubmitted)
	REVISION_REQUESTED_DESIGNER,
	REVISION_SUBMITTED_INSTRUCTOR,

	// 정산 요청 (PayoutRequested)
	PAYOUT_REQUEST_COMPLETED_ADMIN,
	PAYOUT_REQUEST_CANCELLED_ADMIN,
	PAYOUT_REQUEST_REJECTED_ADMIN,

	// auth
	EMAIL_VERIFICATION,
	DESIGNER_SIGNUP_REVIEW_ADMIN,

	// payment
	DEPOSIT_CONFIRM_REQUEST_ADMIN
}
