spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false
  datasource:
    hikari:
      connection-init-sql: "SET SESSION innodb_lock_wait_timeout = 5"

  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION}
      s3:
        endpoint: ${S3_ENDPOINT}
        path-style-access-enabled: true

swagger:
  server-url: http://localhost:8080
  server-description: Local Server
