{
 "title": "AWS RDS",
 "description": "Visualize AWS RDS metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "ap-northeast-2" },
   {
    "name": "dbinstanceidentifier",
    "label": "DBInstanceIdentifier",
    "query": "dimension_values($region, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPUUtilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DatabaseConnections/DiskQueueDepth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "FreeableMemory/FreeStorageSpace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReadIOPS/WriteIOPS/BurstBalance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BurstBalance",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReadLatency/WriteLatency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReadThroughput/WriteThroughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkReceiveThroughput/NetworkTransmitThroughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SwapUsage/BinLogDiskUsage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BinLogDiskUsage",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPUCreditUsage/CPUCreditBalance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReplicaLag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReplicaLag",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}